
name: Lint CI

on:
  - push
  - pull_request    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install --save-dev eslint-config-airbnb-base eslint-plugin-import
          
      - name: Run linter
        run: |
          make lint
